# Generated by Django 3.2.7 on 2021-11-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_alter_rate_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Monobank'), (2, 'Privatbank')], default=2),
        ),
    ]
